answer1 = input("What is the capital of France?")
print(answer1 == "Paris")
answer2 = input("What is the capital of Germany?")
print(answer2 == "Berlin")
answer3 = input("What is the capital of Italy?")
print(answer3 == "Rome")
answer4 = input("What is the capital of Spain?")
print(answer4 == "Madrid")
answer5 = input("What is the capital of The United States of America?")
print(answer5 == "Washington, D.C.")
