adjective = input("Enter an adjective: ")
noun = input("Enter a noun: ")
verb = input("Enter a verb: ")
adverb = input("Enter an adverb: ")
emotion = input("Enter an emotion: ")

print ("Once upon a time, in a " + adjective + " " + noun + ",")
print ("there lived a " + adjective + " " + noun + ".")
print ("Every day, the " + noun + " would " + verb + " " + adverb + ".")
print ("One day, a " + adjective + " " + noun + " appeared")
print ("(and " + verb + " the " + noun + " away.)")
print ("The " + noun + " was " + adjective + " and " + emotion + ".")
