a = 115         #int -> string
b = 3.14        #float -> string
c = "68"        #string -> int
d = "True"      #string -> boolean
e = True        #boolean -> string
f = False       #boolean -> string
g = '10110111'  #byte -> int
h = "2.54"      #string -> float
i = 100         #int -> float
j = 10.0        #float -> int
k = 254         #int -> byte

a = 115
num_str = str(a)
b = 3.14
float_str = str(b)
num_str = "123"
"c" = int(num_str)
bool_val = bool("d")
"e" = str(bool_val)
"f" = str(bool_val)
num = int(g, 2)
"h" = float(float_str)
num_float = float(i)
j = int(num_float)
binary_num = bin(k)
