def product_catalog():
    name = input("Enter item name: ")
    price = float(input("Enter item price: "))
    quantity = int(input("Enter item quantity: "))
    weight = float(input("Enter item weight: "))
    description = input("Enter item description: ")
    print("Item Name: " + name)
    print("Item Price: $" + str(price))
    print("Item Quantity: " + str(quantity))
    print("Item Weight: " + str(weight))
    print("Item Description: " + description)
product_catalog()
product_catalog()
product_catalog()
