def student_profile():
    name = input("Enter your name: ")
    age = input("Enter your age: ")
    hometown = input("Enter your hometown: ")
    favorite_food = input("Enter your favorite food: ")
    favorite_hobby = input("Enter your favorite hobby: ")
    print("My name is " + name + ", I am " + age + " years old, and I am from " + hometown + ".")
    school_name = input("Enter your school name: ")
    grade_level = input("Enter your grade level: ")
    favorite_subject = input("Enter your favorite subject: ")
    study_hours = input("Enter your study hours per week: ")
    graduation_year = input("Enter your graduation year: ")
    print("I attend " + school_name + " , I am in grade " + grade_level + ", my favorite subject is " + favorite_subject + ", I study for " + study_hours + " hours per week, and I will graduate in " + graduation_year + ".")
    dream_school = input("Enter your dream school: ")
    skill2learn = input("Enter a skill you want to learn: ")
    place2visit = input("Enter a place you want to visit: ")
    personal_goal = input("Enter a personal goal: ")
    school_goal = input("Enter a school goal: ")
    print("My dream school is " + dream_school + ", I want to learn " + skill2learn + ", I want to visit " + place2visit + ", my personal goal is " + personal_goal + ", and my school goal is " + school_goal + ".")
    age = int(age)
    grade_level = int(grade_level)
    graduation_year = int(graduation_year)
    study_hours = float(study_hours)
    